"use client";

import { useEffect } from "react";

/**
 * The last thing between a rendering failure and a blank page.
 *
 * Every page here fetches from the backend and renders whatever came back. The
 * fetches have error states; the *rendering* did not. A field that arrived as
 * a string where a number was expected, or an array that arrived as null,
 * throws inside React — and without this file the user gets an empty white
 * screen with the failure only in a console they will never open.
 *
 * What it deliberately does not do is show the error. `error.message` here can
 * be anything the runtime put in it, and this project's rule is that a person
 * sees an authored message and the details go where the operator looks. So the
 * message goes to the console for the developer, and the reader gets a
 * sentence and a way out.
 *
 * The digest is shown because it is the one thing that ties this screen to a
 * server log line, and it is generated by Next rather than derived from data.
 */
export default function RouteError({
  error,
  reset,
}: {
  error: Error & { digest?: string };
  reset: () => void;
}) {
  useEffect(() => {
    // Console, not the page: developer-facing, and not part of the UI contract.
    console.error("Unhandled rendering error", error);
  }, [error]);

  return (
    <div className="mx-auto max-w-lg py-16 text-center">
      <h1 className="text-lg font-semibold text-ink-900">
        This page could not be displayed
      </h1>
      <p className="mt-2 text-sm leading-relaxed text-ink-600">
        Something in the response could not be rendered. The data itself is
        unaffected — nothing was changed by this failure.
      </p>
      {error.digest && (
        <p className="mt-2 font-mono text-xs text-ink-500">
          reference {error.digest}
        </p>
      )}
      <div className="mt-5 flex items-center justify-center gap-3">
        <button
          type="button"
          onClick={reset}
          className="rounded-md bg-accent-700 px-3 py-1.5 text-sm font-medium text-white hover:bg-accent-800 focus:outline-none focus-visible:ring-2 focus-visible:ring-accent-400"
        >
          Try again
        </button>
        <a
          href="/dashboard"
          className="text-sm text-accent-700 underline decoration-accent-300 underline-offset-2 hover:text-accent-900"
        >
          Back to the dashboard
        </a>
      </div>
    </div>
  );
}
